### ISSUE TITLE
Module Install Issue

### ISSUE THREAD

**Issue by m5kro** [xchwarze/frieren-modules#1]
Hi, 

After building a module using yarn and placing the files in `/usr/share/frieren/modules/` it doesn't seem to work on the webUI.

I'm getting the error `Module not found or not available. This error is commonly caused because the .js was not found in the path where it should be.`
In the browser console I'm getting `Failed to load resource: net::ERR_CONTENT_DECODING_FAILED`
I also needed to copy frieren-front to @src/ to successfully build.

How did you build the production modules?

**Comment by m5kro** [comment]
Oh also this is what happens when I try to build without frieren-front at the right spot.
```
❯ yarn build
yarn run v1.22.22
$ vite build
vite v5.2.8 building for production...
✓ 7 modules transformed.
x Build failed in 91ms
error during build:
Error: [vite:load-fallback] Could not load C:\Users\nope\Github-Repos\frieren-modules-test\frieren-front\src/components/PanelCard (imported by src/feature/containers/Screen/index.jsx): ENOENT: no such file or directory, open 'C:\Users\nope\Github-Repos\frieren-modules-test\frieren-front\src\components\PanelCard'
    at async open (node:internal/fs/promises:637:25)
    at async Object.readFile (node:internal/fs/promises:1246:14)
    at async Object.load (file:///C:/Users/nope/Github-Repos/frieren-modules-test/dnsspoof/node_modules/vite/dist/node/chunks/dep-whKeNLxG.js:67116:33)
    at async PluginDriver.hookFirstAndGetPlugin (file:///C:/Users/nope/Github-Repos/frieren-modules-test/dnsspoof/node_modules/rollup/dist/es/shared/node-entry.js:19494:28)
    at async file:///C:/Users/nope/Github-Repos/frieren-modules-test/dnsspoof/node_modules/rollup/dist/es/shared/node-entry.js:18665:33
    at async Queue.work (file:///C:/Users/nope/Github-Repos/frieren-modules-test/dnsspoof/node_modules/rollup/dist/es/shared/node-entry.js:19704:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by m5kro** [comment]
Found the problem. The resulting module.umd.js was uncompressed. Needed to put it through gzip first.

**Comment by xchwarze** [comment]
the nginx instance of frieren is configured to emulate what nginx_static does when installed since the module is not available in openwrt. this is done when building:
```bash
              echo "[*] Prepare project"
              yarn install --frozen-lockfile
              cp config/.env.release .env
              echo "VITE_COMMON_ALIAS='${{ github.workspace }}/build/frieren/frieren-front/src'" >> .env

              echo "[*] Build library"
              yarn build
              
              echo "[*] Generate module package"
              rm -f dist/*.js dist/*.css dist/*.svg
              find dist -type f -name "*.sh" -exec chmod +x {} \;
              find dist -type f -name "*.css.gz" -exec sh -c 'mv "$1" "${1%.css.gz}.css"' _ {} \;
              find dist -type f -name "*.js.gz" -exec sh -c 'mv "$1" "${1%.js.gz}.js"' _ {} \;
              mv dist "${dir##*/}"
```
